export type SystemAuthErrorCode =
  | 'USER_NOT_FOUND'
  | 'ORG_NOT_FOUND'
  | 'ROLE_NOT_FOUND'
  | 'APPROVAL_NOT_FOUND'
  | 'USERNAME_DUPLICATE'
  | 'DIRECTORY_NOT_FOUND'
  | 'PERMISSION_NOT_FOUND'
  | 'DATA_PERMISSION_NOT_FOUND'
  | 'INVALID_ARGUMENT'
  | 'PERMISSION_DENIED'
  | 'APPROVAL_TEMPLATE_NOT_FOUND'
  | 'APPROVAL_STATE_INVALID'
  | 'REMIND_FAILED';
